#! /usr/bin/env perl
# this extension integrates with 'pass' and 'zenity' to select and copy passwords to clipboard
use strict;
use warnings;

use File::Find;

sub on_user_command {
  my ($self,$cmd) = @_;
  if ($cmd eq "pass:copy") {
    my $prefix;
    if (length $ENV{'PASSWORD_STORE_DIR'}) {
      $prefix = $ENV{'PASSWORD_STORE_DIR'};
    } else {
      $prefix = "$ENV{'HOME'}/.password-store";
    }
    my @password_files = ();
    find (sub {push @password_files, $File::Find::name if ( m#^(.*)\.gpg$# ) }, $prefix);
    s/$prefix\/// for @password_files;
    s/\.gpg$// for @password_files;
    my $passwords = join(' ',@password_files);
    my $password = qx#zenity --list --text='Please select a password' --column='Password' --mid-search $passwords 2>/dev/null#;
    chomp $password;
    system("pass","show","-c",$password,"2>/dev/null") if length($password);
  }
}
